spring.profiles.include=local

# Reduce SQL log noise during perf runs
logging.level.org.hibernate.SQL=INFO
logging.level.org.hibernate.type.descriptor.sql=INFO
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=INFO
